apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-demo-app"
  namespace: "default"
spec:
  type: Python
  mode: cluster
  image: "cgrelik/spark_app_demo:latest"
  mainApplicationFile: local:///opt/spark-demo/app.py
  sparkVersion: "3.2.1"
  arguments: ['b4']
  timeToLiveSeconds: 300
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.1
    serviceAccount: airflow-sparkdemo
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.1
