apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-demo-app-{{ ds }}-{{ task_instance.try_number }}"
  namespace: spark-demo
spec:
  type: Python
  mode: cluster
  image: "cgrelik/app_spark_demo:latest"
  mainApplicationFile: local:///opt/spark-demo/app.py
  sparkVersion: "3.2.1"
  arguments: {{ ti.xcom_pull(task_ids='push_args', key='args') }}
  timeToLiveSeconds: 300
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.1
    serviceAccount: airflow-sparkdemo
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.1r
